#! /bin/bash

# enter table name >>>>>>> check if name constraints are not ignored and the name is available

# if everything is ok >>>>>>> create dir in its DB dir with the table name
# then we create 2 files inside that directory 
# 1- table_name
# 2- table_name.md
# after everything has been created sucssesfuly >>> we ask for the table attribute
#add those attributes to the .md file and check if
# 1- attribute name was repeated
# 2- atleast and only 1 primary key entry
# 3- data type for each attribute was set (if not ... we might set it text as default)
# 4- every attribute can be null by default if it wasnt pkey 
# 5- in insertion unique should just check if the value is unique 
# 6- pk makes sure there is a value and it is unique


-----------------------------------------------------
# meta data file structure
# every attribute will be written in 1 line and so on
# first field will be number which represents where is that field should be inserted in data table
# 2nd field is the attribute name
# 3rd field is the data type
# 4th will be the primarykey which will be pk if it is a pk
# 5th autoincreament 
# 6th will be unique >> if it was unique will have the value y otherwise empty
# 7th null or not
# if we want to add more constraints in future we can just add more fields
----------------------------------------------------------------
# columns in the data file will be separated using[ :; ] as [ : ] might not suits the date values and [ ; ] might be used in paragrphs or descriptions but it is rare to have both one after another 
# and each colum will represent an attribute
# in .md file, same separator will be used [ :; ] 
# and each column will be representing a constraint as declared above
